# Defines the configuration settings for the Ragit application for dementia.

web_service:
  name: ragit
  port: 13131
  app_name: ragit

domain:
  title: Alzheimer's Chat Bot
  description: Specializes in  Alzheimer's diagnosis with MRI using AI.
  name: dementia