version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ragit/front_end/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_PORT=${INTERNAL_FRONT_END_PORT}
      - RAG_COLLECTION=${RAG_COLLECTION}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER}
    volumes:
      - ${SHARED_DIR}:/root/ragit-data
    ports:
      - "${EXTERNAL_FRONT_END_PORT}:${INTERNAL_FRONT_END_PORT}"
  backend:
    build:
      context: .
      dockerfile: ragit/backend/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER}
    volumes:
      - ${SHARED_DIR}:/root/ragit-data
    stdin_open: true  # Keep stdin open even if not attached
    tty: true         # Allocate a pseudo-TTY
  db_host:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: