version: "3.8"

services:
    backend:
        build: 
            context: .
            dockerfile: ragit/backend/Dockerfile 
        env_file:
              - .env
        volumes:
              - /home/john/mygen-data:/root/mygen-data

        


  
