# Defines the configuration settings for the Ragit application for dementia.

web_service:
  name: ragit
  port: 13131
  app_name: ragit

domain:
  title: ΤΟ ΘΡΗΣΚΕΥΤΙΚΟ ΣΤΟΙΧΕΙΟ ΣΤΟΥΣ ΟΛΥΜΠΙΑΚΟΥΣ ΑΓΩΝΕΣ ΚΑΤΑ ΤΗΝ ΑΡΧΑΙΟΤΗΤΑ
  description: ΑΡΙΣΤΟΤΕΛΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΕΣΣΑΛΟΝΙΚΗΣ ΤΜΗΜΑ ΠΟΙΜΑΝΤΙΚΗΣ ΚΑΙ ΚΟΙΝΩΝΙΚΗΣ ΘΕΟΛΟΓΙΑΣ
  name: greek